services:
  reverse-proxy: 
    image: traefik:v3.3 
    # Enable web Ui and tell Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80" 
      - "8080:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

